Added role for sidebar-nav
npm/documentation pull request #286
Opened 2022-10-26 13:30 UTC by pavlov-kirill

Demo:

https://user-images.githubusercontent.com/103434939/198038739-c46d54f6-ce2c-4c60-8c6d-dc9b8867e7d4.mov

## References
https://github.com/github/accessibility-audits/issues/2799

2022-11-03 10:57 UTC, 20shivangi approved these changes

2022-11-07 14:25 UTC, amit-avit approved these changes

2022-11-07 15:17 UTC, amit-avit requested changes
After this change the screen reader is announcing the third level link as a text element


https://user-images.githubusercontent.com/8944724/200346295-e1734c38-b9f7-478f-a3b1-0e44b9c849e1.mov

2022-11-08 09:03 UTC, pavlov-kirill commented
> After this change the screen reader is announcing the third level link as a text element
> 
>  Screen.Recording.2022-11-07.at.8.44.40.PM.mov

@amit-avit fixed

https://user-images.githubusercontent.com/103434939/200521255-4c876667-870b-4a89-b678-8e954901982d.mov

<img width="1772" alt="Screen Shot 2022-11-08 at 13 00 55" src="https://user-images.githubusercontent.com/103434939/200521391-1158fdd4-982c-4a73-bf76-7eda2b7ff6ce.png">

2022-11-08 10:29 UTC, amit-avit approved these changes

2022-11-08 10:58 UTC, Seryozha95 approved these changes

2022-11-11 06:06 UTC, merged